config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users,    only: %i[new show create]
  resources :payments, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include AASM
  validates :name, :status, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Email invalid" },
                              uniqueness: { case_sensitive: false },
                              presence: true,
                              length: { minimum: 4, maximum: 254 }

  aasm column: 'status' do
    state :new, initial: true
    state :paid
    state :cancelled

    event :pay do
      transitions from: :new, to: :paid
    end

    event :cancel do
      transitions from: :paid, to: :cancelled
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def set_user
    @user = User.find(params[:id] || params[:user_id])
  end

  def sessioned_user?
    @user.id == session[:current_user_id].to_i
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_user, only: %i[create destroy]

  def create
    begin
      @user.save if @user.pay && sessioned_user?
    rescue AASM::InvalidTransition
      flash.alert = 'Payment not created'
    end
    redirect_to @user
  end

  def destroy
    begin
      @user.save if @user.cancel && sessioned_user?
    rescue AASM::InvalidTransition
      flash.alert = 'Payment not canceled'
    end
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def show
    redirect_to new_user_path unless sessioned_user?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JordyCerebral</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with model: @user do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>
  <%= f.label :name, 'Email' %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Name: <%= @user.name %></h1>
<h2>Email: <%= @user.email %></h2>

<h2>Status: <%= @user.status %></h2>
<% if @user.new? %>
  <%= form_with url: payments_path, method: :post do |form| %>
    <%= form.hidden_field :user_id, value: @user.id %>
    <%= form.submit "Complete Payment" %>
  <% end %>
<% end %>

<% if @user.paid? %>
  <%= form_with url: payment_path, method: :delete do |form| %>
    <%= form.hidden_field :user_id, value: @user.id %>
    <%= form.submit "Cancel" %>
  <% end %>
<% end %>